# permissions for end users to view signozs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: signoz-viewer-role
rules:
- apiGroups:
  - monitor.signoz.io
  resources:
  - signozs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.signoz.io
  resources:
  - signozs/status
  verbs:
  - get
