apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: signoz
type: application
version: 0.1.0

dependencies:
  - name: zookeeper
    repository: "https://charts.bitnami.com/bitnami"
    version: 6.0.0
  - name: kafka
    repository: "https://charts.bitnami.com/bitnami"
    version: 12.0.0
  - name: druid
    repository: "https://charts.helm.sh/incubator"
    version: 0.2.18
  - name: flattener-processor
    repository: "file://./signoz-charts/flattener-processor"
    version: 0.2.0
  - name: query-service
    repository: "file://./signoz-charts/query-service"
    version: 0.2.2
  - name: frontend
    repository: "file://./signoz-charts/frontend"
    version: 0.2.3
